# PATHS DE ARCHIVOS
PATH_BARCOS = 'barcos.csv'
PATH_CANALES = 'canales.csv'
PATH_MERCANCIA = 'mercancia.csv'
PATH_TRIPULANTES = 'tripulantes.csv'

# COMANDOS MENUS 
# AMBOS DEBEN SER STRINGS DIFERENTES DE '00' Y DE CUALQUIER STRING QUE REPRESENTE
# UN NÚMERO ENTRE 1 Y 40. POR ÚLTIMO, DEBEN SER DISTINTOS ENTRE SÍ
COMANDO_VOLVER = '+'
COMANDO_SALIR = '-'

# ENCALLAR
TENDENCIA_ENCALLAR_PASAJEROS = 0.1
TENDENCIA_ENCALLAR_CARGUERO = 0.19
TENDENCIA_ENCALLAR_BUQUE = 0.08

# EVENTO ESPECIAL
PROBABILIDAD_EVENTO_ESPECIAL = 0.12
DINERO_INTOXICACION = 361
TIEMPO_AVERIA_BUQUE = 3

# MERCANCIA
MULTA_PETROLEO = 340
MULTA_ROPA = 541
MULTA_ALIMENTOS = 193

# CANALES
DINERO_INICIAL = 100_000
PROB_BASE_DESENCALLAR = 0.35
COSTO_DESENCALLAR = 773
PONDERADOR_PRINCIPIANTE = 1.6
PONDERADOR_AVANZADO = 1.9
COBRO_USO_PRINCIPIANTE = 586
COBRO_USO_AVANZADO = 1923

# OTROS
CARGA_EXTRA_CARGUERO = 2
